# Generated by Django 4.0.4 on 2022-06-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_history_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='image',
            field=models.TextField(),
        ),
    ]
